### ISSUE TITLE
New primary maintainer for this repository

### ISSUE THREAD

**Issue by christopheralanwest** [cms-hcal-trigger/cms-hcal-debug#2]
The CMS HCAL trigger DPG would like to maintain this software in the future. Github treats the first copy of the repository as special, and so it's somewhat confusing if the owner of this repository no longer maintains the software. Could you do one of the following:

- Transfer ownership of the repository to cms-hcal-trigger
- We can fork the cms-hcal-debug repository to cms-hcal-trigger. Then you could change the README to mention that your fork will not be maintained.

**Comment by matz-e** [comment]
I don't have permissions to create repositories in `cms-hcal-trigger`, hence Github doesn't let me transfer it.

Let me know if you want me to do the transfer (w/ required permissions) or change the README… note that you can also "disassociate" a fork from the original repository.

**Comment by christopheralanwest** [comment]
I invited you to join as a member so I think you should be able to create repositories.

**Comment by matz-e** [comment]
Done. Note that for existing checkouts on lxplus or elsewhere, the repository URL will have to be corrected with:
```
git remote set-url origin git@github.com:cms-hcal-trigger/cms-hcal-debug.git
```
